server:
  port: 8080
camel:
  springboot:
    name: camel
    host: localhost
    bindingMode: auto
    component: servlet
    port: 8080
management:
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s